MS010: false # Enable hard tabs (common in code examples)
MD013: false # Line length - disable for code blocks and long URLs
MD033: false # Allow HTML in markdown (for React component docs)
MD041: false # First line heading level (allow flexibility)
MD024: false # Multiple headings with same content (common in examples)
MD025: false # Multiple top level headings (allow in docs)
MD034: false # Bare URLs (common in code docs)
MD036: false # Emphasis used instead of heading (for API docs)
MD037: false # Spaces inside emphasis markers (common in code examples)
MD038: false # Spaces inside code span markers (common in code examples)
MD039: false # Spaces inside links (common in code examples)
